blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://inertiajs-revamped.com
    about: Report documentation issues on the doc-repository. 

  - name: Support Question
    url: https://github.com/inertiajs-revamped/inertia/discussions
    about: Post your question on the discussion board instead of our issue tracker.

  - name: Discord Chat
    url: https://discord.gg/Hn5bDDvTKX
    about: Join our Discord chat, if you need additional help.
